name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Login to Render
        run: |
          echo ${{ secrets.RENDER_TOKEN }} | render login

      - name: Build and push to Render
        run: |
          render build -- --no-cache
          render deploy
